### ISSUE TITLE
WithDur output format could be improved

### ISSUE THREAD

**Issue by joshrendek** [secureworks/logger#4]
When doing 

```go
logger.Debug().WithDur("total_time", time.Since(startTime))
```

I get 

```json
"total_time":33256358542
```

If I swap to using a string:

```go
logger.Debug().WithStr("total_time", time.Since(startTime).String())
```

Produces the expected / more useful output

```json
"total_time":"30.99228175s"
```

**Comment by hews** [comment]
This is a really good point: it's non-obvious for me that this will output Unix nano.

However, I think a. *making it a string representation of a number*, and b. *making it default to seconds*, are both kind of iffy propositions. [Defaulting to Unix nano is expected by DD's "duration" standard field, eg.](https://docs.datadoghq.com/logs/log_configuration/attributes_naming_convention/#performance)

I would not be against updating the interface to something like:

```go
type proposedDurationFieldSetters interface {
	// I do not like WithDur ;)
    
	// WithDurations is a type-safe convenience for injecting a 
	// time.Duration field (or time.Duration fields: how they are stored is
	// implementation-specific).
	//
	// WithDuration values are Unix nanosecond timestamps encoded
	// in JSON as numbers. Use WithDurationStrings for more human-
	// readable string values.
	WithDurations(fieldName string, dur ...time.Duration) Entry

	// WithDurationStrings is a type-safe convenience for injecting a 
	// time.Duration field (or time.Duration fields: how they are stored is
	// implementation-specific).
	//
	// WithDurationStrings values are human-readable strings, 
	// formatted using the time.Duration String method.
	WithDurationStrings(fieldName string, dur ...time.Duration) Entry
}
```

@iaburton thoughts?

**Comment by iaburton** [comment]
@hews if you don't smirk when you type `WithDur` we may reach an impasse.

Again I'd like to try to keep the interface as small as possible. Instead maybe this should be an option for "human readable time/numbers" ? Some people might want that, others might not care since only computers will be parsing/using it. (Though I suppose in the latters case you may not want/care about JSON either).

For example zerolog has on it's version (which our driver calls)
>Dur adds the field key with duration d stored as zerolog.DurationFieldUnit. If zerolog.DurationFieldInteger is true, durations are rendered as integer instead of float. 

Those are globals that would actually change it for our driver (a function I don't like much, globals, but users of zerolog could do that).

Conversely logrus does not have a "duration" method and seems to rely on the types own MarshalJSON/MarshalText/encoding if not reflect. I'm assuming @joshrendek is using the logrus driver.

For behavior related things I'm leaning towards options (that can be driver specific or not) rather than interface methods. _Creators_ of the loggers (main) / choosers of the drivers (main) should have control over that behavior, not the _users_ (modules/consumers). Similarly to how go.mod/deps work in Go, or the database/sql interface this was partially based on.
Thoughts @hews ?

**Comment by hews** [comment]
> Creators of the loggers (main) / choosers of the drivers (main) should have control over that behavior, not the users (modules/consumers).

This is a good point: time / date / duration and other such should match across all logs for an instance. Driver-specific options would be smart here, but the format may be a big enough issue that we want to offer up a new shared interface that all drivers need to implement so that people can easily identify a way to set this:

```go
logger, err := log.Open("logrus", nil, log.FormatDurationReadable(), log.FormatTimeUnixNano())
```

**Comment by hews** [comment]
Alright, I am going to put an update into v2 that will make sure that the expected output aligns across all field types, including this.
